version: "3.6"

services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: shrink_prod
      POSTGRES_PASSWORD: postgres
    image: postgres:15.6-alpine
    ports:
      - "15432:5432"

  app:
    restart: on-failure
    depends_on:
      - db
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db/shrink_prod"
      PHX_HOST: example.com
      PORT: "4000"
      # mix phx.gen.secret
      SECRET_KEY_BASE: "xe2W8nL5AYfMaB16dhTfMkH3gYDP6DJosEs+/QfirOICJ12NaD12XDre1pLcZn+S"
    ports:
      - "4001:4000"
